# Generated by Django 5.2.11 on 2026-02-08 17:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("image", models.ImageField(upload_to="blogs/")),
            ],
        ),
    ]
